# -*- coding: utf-8 -*-
"""App.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iIaHghSPnT6vKZH_kR7M4GlPmK1s4uLY
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

def build_recommendation_engine(file_path):
    # 1. Load the dataset
    df = pd.read_csv(file_path)

    # 2. Filter for Movies only and handle missing values
    movies_df = df[df['type'] == 'Movie'].copy()
    movies_df = movies_df.dropna(subset=['name', 'genre'])
    movies_df['name'] = movies_df['name'].str.strip()

    # 3. Vectorize the Genres using TF-IDF
    # This converts text genres into a numerical matrix
    tfidf = TfidfVectorizer(stop_words='english')
    tfidf_matrix = tfidf.fit_transform(movies_df['genre'])

    # 4. Compute Cosine Similarity
    # This measures how similar each movie is to every other movie
    cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

    # Create a mapping of movie names to indices
    indices = pd.Series(movies_df.index, index=movies_df['name'].str.lower()).drop_duplicates()

    return movies_df, cosine_sim, indices

def get_recommendations(title, movies_df, cosine_sim, indices, n=5):
    title = title.lower()
    if title not in indices:
        return f"Movie '{title}' not found in the database."

    # Get the internal index of the movie
    idx = indices[title]

    # If there are duplicate names, take the first one
    if isinstance(idx, pd.Series):
        idx = idx[0]

    # Get position of the movie in the similarity matrix
    movie_pos = movies_df.index.get_loc(idx)

    # Get similarity scores for all movies with that movie
    sim_scores = list(enumerate(cosine_sim[movie_pos]))

    # Sort movies based on similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the top N similar movies (skipping the movie itself)
    sim_scores = sim_scores[1:n+1]

    # Get the movie indices
    movie_indices = [i[0] for i in sim_scores]

    # Return the titles, genres, and ratings
    return movies_df.iloc[movie_indices][['name', 'genre', 'rating']]

# --- Main Execution ---
file_path = 'anime (1).csv'
movies_df, cosine_sim, indices = build_recommendation_engine(file_path)

# Test the recommendation engine
search_title = "Toy Story (1995)"
print(f"Recommendations for '{search_title}':")
recommendations = get_recommendations(search_title, movies_df, cosine_sim, indices)
print(recommendations)

pip install streamlit pandas scikit-learn

import streamlit as st
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# --- APP CONFIGURATION ---
st.set_page_config(page_title="Anime Movie Recommender", layout="wide")

# --- DATA LOADING & ENGINE ---
@st.cache_data  # This prevents reloading the data every time you click a button
def load_data():
    df = pd.read_csv('anime (1).csv')
    movies_df = df[df['type'] == 'Movie'].copy()
    movies_df = movies_df.dropna(subset=['name', 'genre'])
    movies_df['name'] = movies_df['name'].str.strip()
    return movies_df

@st.cache_resource
def build_engine(movies_df):
    tfidf = TfidfVectorizer(stop_words='english')
    tfidf_matrix = tfidf.fit_transform(movies_df['genre'])
    cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)
    indices = pd.Series(movies_df.index, index=movies_df['name']).drop_duplicates()
    return cosine_sim, indices

# --- UI DESIGN ---
st.title("🎬 Anime Movie Recommender")
st.write("Find your next favorite anime movie based on genres!")

# Load data
movies_df = load_data()
cosine_sim, indices = build_engine(movies_df)

# Sidebar/Search
movie_list = movies_df['name'].values
selected_movie = st.selectbox("Type or select an anime movie:", movie_list)

if st.button('Get Recommendations'):
    # Get index
    idx = indices[selected_movie]
    if isinstance(idx, pd.Series):
        idx = idx[0]

    movie_pos = movies_df.index.get_loc(idx)
    sim_scores = list(enumerate(cosine_sim[movie_pos]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:6]

    movie_indices = [i[0] for i in sim_scores]
    recommendations = movies_df.iloc[movie_indices]

    # Display results
    st.subheader(f"Top 5 movies similar to '{selected_movie}':")

    for i, row in recommendations.iterrows():
        with st.container():
            col1, col2 = st.columns([3, 1])
            with col1:
                st.markdown(f"### {row['name']}")
                st.caption(f"**Genres:** {row['genre']}")
            with col2:
                st.metric("Rating", f"{row['rating']}/10")
            st.divider()