# -*- coding: utf-8 -*-
"""requirements.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qARpmt0xoKE_Obo8Hc4zz5NLoUFtX3Wn
"""

!pip install streamlit
import streamlit
import pandas
import sklearn